// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = "9f6427cc-81eb-4757-9ef1-2f5bccf15e1a";

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onIsMovingChange();
void onTotalCollisionsChange();

String isMoving;
int totalCollisions;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(isMoving, READWRITE, ON_CHANGE, onIsMovingChange);
  ArduinoCloud.addProperty(totalCollisions, READWRITE, ON_CHANGE, onTotalCollisionsChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
